import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Initialize database and cron jobs on server startup
if (typeof window === 'undefined') {
  // This only runs on the server side
  import('@/lib/db/init.js').catch(err => 
    console.error('[LAYOUT] Failed to initialize database:', err)
  );
  
  import('@/jobs/cronServer.js').then(({ startCronJobs }) => {
    if (!global.CRON_JOBS_STARTED) {
      startCronJobs();
      global.CRON_JOBS_STARTED = true;
    }
  }).catch(err => 
    console.error('[LAYOUT] Failed to start cron jobs:', err)
  );
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
